import argparse
import os

import h5py
import iscetest
import numpy as np
import numpy.testing as npt
from nisar.workflows import prepare_insar_hdf5, rubbersheet
from nisar.workflows.rubbersheet_runconfig import RubbersheetRunConfig
from nisar.products.insar.product_paths import RIFGGroupsPaths


def test_run_rubbersheet():
    '''
    Check if rubbersheet runs without crashing
    '''
    # Load yaml file
    test_yaml = os.path.join(iscetest.data, 'insar_test.yaml')
    with open(test_yaml) as fh_test_yaml:
        test_yaml = fh_test_yaml.read().replace('@ISCETEST@', iscetest.data). \
            replace('@TEST_OUTPUT@', 'rifg.h5'). \
            replace('@TEST_PRODUCT_TYPES@', 'RIFG').\
            replace('@TEST_RDR2GEO_FLAGS@', 'True')

    # Create CLI input namespace with yaml text instead of filepath
    args = argparse.Namespace(run_config_path=test_yaml, log_file=False)

    # Initialize rubbersheet runconfig object
    runconfig = RubbersheetRunConfig(args)
    runconfig.geocode_common_arg_load()

    # Prepare output HDF5 products
    prepare_insar_hdf5.run(runconfig.cfg)

    # Run rubbersheet
    rubbersheet.run(runconfig.cfg,
                    output_hdf5=\
                        runconfig.cfg['product_path_group']['sas_output_file'])


def test_validate_rubbersheet():
    '''
    Validate culled offsets generated by rubbersheet
    '''

    # Create RIFG obj to avoid hard-coded paths to RIFG datasets
    scratch_path = '.'
    group_path = f'{RIFGGroupsPaths().SwathsPath}/frequencyA/pixelOffsets/HH'

    with h5py.File(os.path.join(scratch_path, 'rifg.h5'), 'r') as h_rifg:
        # Check that rubbersheeted offsets are close to zero
        # (note, we are cross-correlating an image with itself,
        #  the culled offsets should therefore be zero)
        datasets = ['alongTrackOffset', 'slantRangeOffset']

        for data in datasets:
            product_path = os.path.join(group_path, data)
            offset = h_rifg[product_path][()]
            npt.assert_allclose(np.abs(offset), 0, atol=1e-6)


def test_resample_offsets_to_slc(tmp_path):
    '''
    Check that offsets are placed at their offsets grid positions on the
    reference RSLC grid, with edge values extended beyond the grid
    '''
    length, width = 100, 120
    off_az_pos = 20. + 8. * np.arange(8)
    off_rg_pos = 30. + 8. * np.arange(9)

    # Linear offsets, reproduced exactly by bilinear interpolation
    def offset(line, col):
        return 0.01 * line + 0.02 * col + 1.

    lines, cols = np.meshgrid(off_az_pos, off_rg_pos, indexing='ij')
    off_path = str(tmp_path / 'culled_offsets')
    rubbersheet._write_to_disk(off_path, offset(lines, cols))

    lines, cols = np.meshgrid(np.arange(length), np.arange(width),
                              indexing='ij')
    expected = offset(np.clip(lines, off_az_pos[0], off_az_pos[-1]),
                      np.clip(cols, off_rg_pos[0], off_rg_pos[-1]))

    for lines_per_block in [7, length]:
        out_path = str(tmp_path / f'resampled_offsets_{lines_per_block}')
        rubbersheet._resample_offsets_to_slc(off_path, out_path,
                                             off_az_pos, off_rg_pos,
                                             length, width, lines_per_block)
        npt.assert_allclose(rubbersheet._open_raster(out_path), expected,
                            atol=1e-12)

    # Sum to geometry offsets in the same pass; invalid geometry offsets stay
    geo = np.full((length, width), 0.5)
    geo[3, 4] = -1e6
    geo_path = str(tmp_path / 'geo.off')
    rubbersheet._write_to_disk(geo_path, geo)
    out_path = str(tmp_path / 'sum.off')
    rubbersheet._resample_offsets_to_slc(off_path, out_path, off_az_pos,
                                         off_rg_pos, length, width, 7,
                                         geo_off_path=geo_path)
    # 7 lines per block: last block is partial
    npt.assert_allclose(rubbersheet._open_raster(out_path),
                        np.where(geo == -1e6, -1e6, expected + 0.5),
                        atol=1e-12)

    # Offsets computed on read (fine resampling) equal the written ones
    # bit for bit, for any row/column block
    full = rubbersheet._open_raster(out_path)
    out_dir = tmp_path / 'rubbersheet'
    out_dir.mkdir()
    for culled, name in rubbersheet.RUBBERSHEET_OFFSETS:
        rubbersheet._write_to_disk(str(out_dir / culled), offset(
            *np.meshgrid(off_az_pos, off_rg_pos, indexing='ij')))
        rubbersheet._write_to_disk(str(tmp_path / name), geo)
    rubbersheet._save_rubbersheet_offsets(out_dir, tmp_path, off_az_pos,
                                          off_rg_pos, length, width, False)
    az, rg = rubbersheet.open_resample_offsets(out_dir, (length, width))
    for reader in (az, rg):
        assert reader.shape == (length, width)
        npt.assert_array_equal(reader[:, :], full)
        npt.assert_array_equal(reader[10:17, 33:90], full[10:17, 33:90])
    # Without the on-read spec: the full-resolution rasters
    rubbersheet._save_rubbersheet_offsets(out_dir, tmp_path, off_az_pos,
                                          off_rg_pos, length, width, True)
    (out_dir / rubbersheet.RUBBERSHEET_SPEC).unlink()
    az, _ = rubbersheet.open_resample_offsets(out_dir, (length, width))
    npt.assert_array_equal(az[:, :], full)


if __name__ == "__main__":
    test_run_rubbersheet()
    test_validate_rubbersheet()
